version: '2'
services:
  ide:
    image: pcstudio-novnc:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - x11
networks:
  x11:
